# Generated by Django 5.1.1 on 2024-10-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('lettre', models.TextField()),
                ('statut', models.IntegerField(choices=[(0, 'En cours'), (1, 'Refusé'), (2, 'Accepté')], default=0)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.offres')),
            ],
        ),
    ]
