# Generated by Django 5.1.1 on 2024-10-24 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0005_postuler_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuler',
            name='statut',
            field=models.IntegerField(choices=[(0, 'En cours'), (1, 'Refusée'), (2, 'Acceptée')], default=0),
        ),
        migrations.AlterField(
            model_name='postuler',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
